name: integration_tests
description: An integration test suite for the Flutter Architecture Samples

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  test: any
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
